### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by muhammedfurkan** [watzon/telethon-session-mongo#4]
```AttributeError: 'NoneType' object has no attribute 'id'
[ERROR/2021-10-14 14:27:54,940] asyncio: Task exception was never retrieved
future: <Task finished coro=<UpdateMethods._dispatch_update() done, defined at /usr/local/lib/python3.7/dist-packages/telethon/client/updates.py:399> exception=AttributeError("'NoneType' object has no attribute 'id'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 408, in _dispatch_update
    await self._get_difference(update, channel_id, pts_date)
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/updates.py", line 544, in _get_difference
    where = await self.get_input_entity(types.PeerChannel(channel_id))
  File "/usr/local/lib/python3.7/dist-packages/telethon/client/users.py", line 430, in get_input_entity
    return self.session.get_input_entity(peer)
  File "/usr/local/lib/python3.7/dist-packages/telethon/sessions/memory.py", line 218, in get_input_entity
    result = self.get_entity_rows_by_id(key, exact)
  File "/usr/local/lib/python3.7/dist-packages/telemongo/telemongo.py", line 191, in get_entity_rows_by_id
    return (ent.id, ent.hash)
AttributeError: 'NoneType' object has no attribute 'id'
```

**I'm getting this error `telemongo.py` in [191 line](https://github.com/watzon/telethon-session-mongo/blob/8c49454468f91cbcc7ec916888798c1c714c86a8/telemongo/telemongo.py#L191)**

**Comment by watzon** [comment]
Closed with v0.2.1
